# This workflow is written specifically for Jam3/nextjs-boilerplate
# It uploads all contents inside the ./out/ folder generated on build:prod:static process to an AWS S3 account

name: Github Action S3 Deploy

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      GTM_ID:
        required: true
        type: string
      GTM_PARAMS:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      CONTENTFUL_SPACE_ID:
        required: true
      CONTENTFUL_DELIVERY_API_ACCESS_TOKEN:
        required: true
      CONTENTFUL_PREVIEW_API_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      WEBSITE_SITE_URL:
        required: true
      S3_ORIGIN_BUCKET:
        required: true
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@8

      - name: Clear Prepare Script
        run: npm set-script prepare ""

      - name: Install dependencies
        run: npm ci

      - name: Run Linters
        run: npm run linters-ci

      - name: Build NextJS static site
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          GTM_ID: ${{ inputs.GTM_ID }}
          GTM_PARAMS: ${{ inputs.GTM_PARAMS }}
          WEBSITE_SITE_URL: ${{ secrets.WEBSITE_SITE_URL }}
          CONTENTFUL_ENVIRONMENT: ${{ inputs.CONTENTFUL_ENVIRONMENT }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_DELIVERY_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_API_ACCESS_TOKEN }}
          CONTENTFUL_PREVIEW_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_API_ACCESS_TOKEN }}
          S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}

      - name: S3 Deploy
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
